### ISSUE TITLE
 CUDA device-side assert (likely KV cache / attention_mask mismatch during generation)

### ISSUE THREAD

**Issue by JieWang24** [fla-org/hybrid-distillation#3]
Hi, thank you for the great work and for releasing this project.

I ran into an evaluation issue while reproducing the results. I created a fresh environment and followed the README steps strictly. Stage 1 and Stage 2 training finished successfully, but when I try to evaluate on RULER, the script crashes with a FlashAttention dtype error.

### Steps to reproduce
After finishing Stage 1 and Stage 2, I run:
```bash
bash eval.sh /path/to/your/checkpoint
``` 
The evaluation crashes with the following error:
```
RuntimeError: FlashAttention only support fp16 and bf16 data type
``` 
Full traceback:
```

[rank0]: Traceback (most recent call last):
[rank0]:   File ".../hybrid-distillation/eval/harness.py", line 25, in <module>
[rank0]:     cli_evaluate()
[rank0]:   File ".../lm-evaluation-harness/lm_eval/__main__.py", line 10, in cli_evaluate
[rank0]:     parser.execute(args)
[rank0]:   File ".../lm-evaluation-harness/lm_eval/_cli/harness.py", line 60, in execute
[rank0]:     args.func(args)
[rank0]:   File ".../lm-evaluation-harness/lm_eval/_cli/run.py", line 379, in _execute
[rank0]:     results = simple_evaluate(
[rank0]:               ^^^^^^^^^^^^^^^^
[rank0]:   File ".../lm-evaluation-harness/lm_eval/utils.py", line 491, in _wrapper
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lm-evaluation-harness/lm_eval/evaluator.py", line 365, in simple_evaluate
[rank0]:     results = evaluate(
[rank0]:               ^^^^^^^^^
[rank0]:   File ".../lm-evaluation-harness/lm_eval/utils.py", line 491, in _wrapper
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lm-evaluation-harness/lm_eval/evaluator.py", line 594, in evaluate
[rank0]:     resps = getattr(lm, reqtype)(cloned_reqs)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lm-evaluation-harness/lm_eval/models/huggingface.py", line 1466, in generate_until
[rank0]:     cont = self._model_generate(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lm-evaluation-harness/lm_eval/models/huggingface.py", line 999, in _model_generate
[rank0]:     return self.model.generate(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/transformers/generation/utils.py", line 2625, in generate
[rank0]:     result = self._sample(
[rank0]:              ^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/transformers/generation/utils.py", line 3606, in _sample
[rank0]:     outputs = self(**model_inputs, return_dict=True)
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/transformers/utils/deprecation.py", line 172, in wrapped_func
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../hybrid-distillation/distill_model/modeling_distilled_student.py", line 473, in forward
[rank0]:     outputs = self.model(
[rank0]:               ^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../hybrid-distillation/distill_model/modeling_distilled_student.py", line 349, in forward
[rank0]:     layer_outputs = layer(
[rank0]:                     ^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../hybrid-distillation/distill_model/modeling_distilled_student.py", line 184, in forward
[rank0]:     hidden_states, attentions, past_key_values = self.attn(
[rank0]:                                                  ^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/fla/layers/attn.py", line 142, in forward
[rank0]:     o = flash_attn_varlen_func(
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/flash_attn/flash_attn_interface.py", line 1448, in flash_attn_varlen_func
[rank0]:     return FlashAttnVarlenFunc.apply(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/autograd/function.py", line 575, in apply
[rank0]:     return super().apply(*args, **kwargs)  # type: ignore[misc]
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/flash_attn/flash_attn_interface.py", line 930, in forward
[rank0]:     out_padded, softmax_lse, S_dmask, rng_state = _wrapped_flash_attn_varlen_forward(
[rank0]:                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/_ops.py", line 1123, in __call__
[rank0]:     return self._op(*args, **(kwargs or {}))
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/_library/autograd.py", line 113, in autograd_impl
[rank0]:     result = forward_no_grad(*args, Metadata(keyset, keyword_only_args))
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/_library/autograd.py", line 40, in forward_no_grad
[rank0]:     result = op.redispatch(keyset & _C._after_autograd_keyset, *args, **kwargs)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/_ops.py", line 728, in redispatch
[rank0]:     return self._handle.redispatch_boxed(keyset, *args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/_library/custom_ops.py", line 305, in backend_impl
[rank0]:     result = self._backend_fns[device_type](*args, **kwargs)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/_compile.py", line 32, in inner
[rank0]:     return disable_fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/_dynamo/eval_frame.py", line 745, in _fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/_library/custom_ops.py", line 337, in wrapped_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/flash_attn/flash_attn_interface.py", line 170, in _flash_attn_varlen_forward
[rank0]:     out, softmax_lse, S_dmask, rng_state = flash_attn_gpu.varlen_fwd(
[rank0]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: FlashAttention only support fp16 and bf16 data type
``` 
I checked the checkpoint/config and it indicates torch_dtype = bfloat16 (bf16). 
However, the error still suggests that the tensors passed into FlashAttention are not fp16/bf16 at runtime.

### Question
Have you encountered this issue before, or do you have any suggestions on what might be causing the dtype mismatch during evaluation? 
For example, should I explicitly enforce bf16/fp16 during eval.sh (e.g., autocast / --dtype / --bf16 flags), or disable FlashAttention for evaluation?

Thanks a lot for your help!

**Comment by JieWang24** [comment]
## Update: upgrading Transformers fixes dtype issue, but now hits CUDA device-side assert (likely KV cache / attention_mask mismatch during generation)

Hi again — quick update on my side.

I upgraded `transformers` from **4.53.3** to **4.57.6**. The previous FlashAttention dtype error is gone, but now evaluation fails with a more severe CUDA error:

### New error
```text
.../pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
...
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
``` 

<details>
<summary>Full traceback </summary>

```
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [121,0,0], thread: [29,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [121,0,0], thread: [30,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [121,0,0], thread: [31,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
[rank0]: Traceback (most recent call last):
[rank0]:   File ".../hybrid-distillation/eval/harness.py", line 25, in <module>
[rank0]:     cli_evaluate()
[rank0]:   File ".../lm-evaluation-harness/lm_eval/__main__.py", line 10, in cli_evaluate
[rank0]:     parser.execute(args)
[rank0]:   File ".../lm-evaluation-harness/lm_eval/_cli/harness.py", line 60, in execute
[rank0]:     args.func(args)
[rank0]:   File ".../lm-evaluation-harness/lm_eval/_cli/run.py", line 379, in _execute
[rank0]:     results = simple_evaluate(
[rank0]:               ^^^^^^^^^^^^^^^^
[rank0]:   File ".../lm-evaluation-harness/lm_eval/utils.py", line 491, in _wrapper
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lm-evaluation-harness/lm_eval/evaluator.py", line 365, in simple_evaluate
[rank0]:     results = evaluate(
[rank0]:               ^^^^^^^^^
[rank0]:   File ".../lm-evaluation-harness/lm_eval/utils.py", line 491, in _wrapper
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lm-evaluation-harness/lm_eval/evaluator.py", line 594, in evaluate
[rank0]:     resps = getattr(lm, reqtype)(cloned_reqs)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lm-evaluation-harness/lm_eval/models/huggingface.py", line 1466, in generate_until
[rank0]:     cont = self._model_generate(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lm-evaluation-harness/lm_eval/models/huggingface.py", line 999, in _model_generate
[rank0]:     return self.model.generate(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/transformers/generation/utils.py", line 2566, in generate
[rank0]:     result = decoding_method(
[rank0]:              ^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/transformers/generation/utils.py", line 2786, in _sample
[rank0]:     outputs = self(**model_inputs, return_dict=True)
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/transformers/utils/deprecation.py", line 172, in wrapped_func
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../hybrid-distillation/distill_model/modeling_distilled_student.py", line 507, in forward
[rank0]:     outputs = self.model(
[rank0]:               ^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../hybrid-distillation/distill_model/modeling_distilled_student.py", line 377, in forward
[rank0]:     layer_outputs = layer(
[rank0]:                     ^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../hybrid-distillation/distill_model/modeling_distilled_student.py", line 206, in forward
[rank0]:     hidden_states, attentions, past_key_values = self.attn(
[rank0]:                                                  ^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/fla/layers/attn.py", line 139, in forward
[rank0]:     q, (k, v), indices_q, cu_seqlens, max_seq_lens = unpad_input(q, (k, v), attention_mask, q_len)
[rank0]:                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/fla/layers/utils.py", line 145, in unpad_input
[rank0]:     state = tuple(
[rank0]:             ^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/fla/layers/utils.py", line 146, in <genexpr>
[rank0]:     index_first_axis(rearrange(s, "b s ... -> (b s) ..."), indices_k)
[rank0]:   File ".../lib/python3.12/site-packages/torch/autograd/function.py", line 575, in apply
[rank0]:     return super().apply(*args, **kwargs)  # type: ignore[misc]
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File ".../lib/python3.12/site-packages/fla/layers/utils.py", line 25, in forward
[rank0]:     return torch.gather(
[rank0]:            ^^^^^^^^^^^^^
[rank0]: RuntimeError: CUDA error: device-side assert triggered
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

</details>

I printed the shapes of the involved tensors and it seems the issue is related to generation with full attention + KV cache.

At `fla/layers/attn.py line 139`:
```
q, (k, v), indices_q, cu_seqlens, max_seq_lens = unpad_input(q, (k, v), attention_mask, q_len)
``` 
I expected the (k, v) state to have shape like [batch_size, seq_len, ...], matching the attention_mask.
However, what I observe at runtime is that (k, v) is shaped like [batch_size, 1, ...], which does not align with the mask (still corresponding to the full sequence). This mismatch likely causes invalid gather indices and triggers the index out of bounds assertion / device-side assert.

It feels like the KV cache is not being updated (or not being passed correctly) for the full-attention path during incremental decoding.

### Minimal reproduction

This is reproducible even without the evaluation harness:

+ initialize the model from the checkpoint

+ construct a small batch of inputs

+ call model.generate(...)

It crashes with the same error.

### Question

Does the current implementation support generate() (incremental decoding) in this setup?  
Any guidance on the recommended evaluation setup or a possible fix would be greatly appreciated. Thanks a lot!

**Comment by yanhong-lbh** [comment]
Hi! Very sorry for the delayed reply.

Could you try if this patch works? 

```
# eval/harness.py

from __future__ import annotations

import fla  # noqa
from lm_eval.__main__ import cli_evaluate
from lm_eval.api.registry import register_model
from lm_eval.models.huggingface import HFLM

from distill_model.config_distilled_student import StudentConfig
from distill_model.modeling_distilled_student import StudentModel, StudentForCausalLM
from transformers import AutoConfig, AutoModelForCausalLM

import torch
import flash_attn.flash_attn_interface

import torch
import flash_attn.flash_attn_interface

import torch
import flash_attn.flash_attn_interface

import torch
import torch.nn.functional as F
import flash_attn.flash_attn_interface

# ==============================================================================
# PATCH 1: FlashAttention (Fixes "only support fp16/bf16")
# ==============================================================================
# We wrap the kernel to ensure inputs are ALWAYS BF16 and CONTIGUOUS.
_original_flash_attn_varlen_func = flash_attn.flash_attn_interface.flash_attn_varlen_func

def _patched_flash_attn_varlen_func(q, k, v, *args, **kwargs):
    original_dtype = q.dtype
    
    # 1. Force inputs to BFloat16 (Kernel requirement)
    if q.dtype == torch.float32: q = q.to(torch.bfloat16)
    if k.dtype == torch.float32: k = k.to(torch.bfloat16)
    if v.dtype == torch.float32: v = v.to(torch.bfloat16)
    
    # 2. Force memory to be contiguous (Prevents illegal memory access)
    if not q.is_contiguous(): q = q.contiguous()
    if not k.is_contiguous(): k = k.contiguous()
    if not v.is_contiguous(): v = v.contiguous()
    
    # 3. Run the kernel
    output = _original_flash_attn_varlen_func(q, k, v, *args, **kwargs)
    
    # 4. Cast output back to Float32 if the model expects it
    if original_dtype == torch.float32 and output.dtype != torch.float32:
        output = output.to(torch.float32)
        
    return output

# Apply Patch 1
flash_attn.flash_attn_interface.flash_attn_varlen_func = _patched_flash_attn_varlen_func
try:
    import fla.layers.attn
    fla.layers.attn.flash_attn_varlen_func = _patched_flash_attn_varlen_func
    print(">>> [Patch] Successfully patched FlashAttention (Safe Cast & Contiguous)")
except ImportError:
    pass

# ==============================================================================
# PATCH 2: SwiGLU (Fixes "illegal memory access")
# ==============================================================================
# We bypass the crashing Triton kernel entirely and use standard PyTorch.
# Math: SwiGLU(g, x) = SiLU(g) * x

def _patched_swiglu_fwd(x, y):
    # x is the gate, y is the value
    # Standard PyTorch implementation - Safe, stable, no segfaults.
    return F.silu(x) * y

# Apply Patch 2
try:
    import fla.modules.activations
    fla.modules.activations.swiglu_fwd = _patched_swiglu_fwd
    print(">>> [Patch] Successfully patched SwiGLU (Bypassed Triton Kernel)")
except ImportError:
    print(">>> [Patch] Warning: Could not patch SwiGLU (Import failed)")

print(">>> Monkeypatches applied: Model is safe for Mixed Precision evaluation")

AutoConfig.register('student', StudentConfig, exist_ok=True)
AutoModelForCausalLM.register(StudentConfig, StudentForCausalLM, exist_ok=True)

@register_model('fla')
class FlashLinearAttentionLMWrapper(HFLM):
    def __init__(self, **kwargs) -> FlashLinearAttentionLMWrapper:
        # TODO: provide options for doing inference with different kernels
        super().__init__(**kwargs)


if __name__ == "__main__":
    cli_evaluate()

```


Let me know if it does not work!

**Comment by JieWang24** [comment]
Thanks a lot for the quick reply and the helpful suggestion!

I followed your recommendation and downgraded transformers from 4.57.6 back to 4.53.3. After reverting, the evaluation now runs successfully.

Really appreciate your guidance and for maintaining this project — thank you!

**Comment by yanhong-lbh** [comment]
Thanks for the update! :)
